//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2021. 04. 01. 16:17:53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Internal;
using Microsoft.EntityFrameworkCore.Metadata;
using WPF_PhoneBook;
using Microsoft.Extensions.Configuration;

namespace PhoneBook
{

    public partial class ccnPhoneBook : DbContext
    {

        public ccnPhoneBook() :
            base()
        {
            OnCreated();
        }

        public ccnPhoneBook(DbContextOptions<ccnPhoneBook> options) :
            base(options)
        {
            OnCreated();
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured ||
                (!optionsBuilder.Options.Extensions.OfType<RelationalOptionsExtension>().Any(ext => !string.IsNullOrEmpty(ext.ConnectionString) || ext.Connection != null) &&
                 !optionsBuilder.Options.Extensions.Any(ext => !(ext is RelationalOptionsExtension) && !(ext is CoreOptionsExtension))))
            {
                optionsBuilder.UseSqlServer(GetConnectionString("cnPhoneBook"));
            }
            CustomizeConfiguration(ref optionsBuilder);
            base.OnConfiguring(optionsBuilder);
        }

        private static string GetConnectionString(string connectionStringName)
        {
            //  var configurationBuilder = new ConfigurationBuilder().AddJsonFile("appsettings.json", optional: true, reloadOnChange: false);
            //  var configuration = configurationBuilder.Build();
            //  return configuration.GetConnectionString(connectionStringName);

            return "Data Source=(LocalDB)\\MSSQLLocalDB;Initial Catalog=WpfPhoneBook;Integrated Security=True;Persist Security Info=True";
        }

        partial void CustomizeConfiguration(ref DbContextOptionsBuilder optionsBuilder);

        public virtual DbSet<Person> People
        {
            get;
            set;
        }

        public virtual DbSet<Number> Numbers
        {
            get;
            set;
        }

        public virtual DbSet<City> Cities
        {
            get;
            set;
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            this.PersonMapping(modelBuilder);
            this.CustomizePersonMapping(modelBuilder);

            this.NumberMapping(modelBuilder);
            this.CustomizeNumberMapping(modelBuilder);

            this.CityMapping(modelBuilder);
            this.CustomizeCityMapping(modelBuilder);

            RelationshipsMapping(modelBuilder);
            CustomizeMapping(ref modelBuilder);
        }

        #region Person Mapping

        private void PersonMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Person>().ToTable(@"Person");
            modelBuilder.Entity<Person>().Property(x => x.Id).HasColumnName(@"Id").IsRequired().ValueGeneratedOnAdd();
            modelBuilder.Entity<Person>().Property(x => x.Name).HasColumnName(@"Name").IsRequired().ValueGeneratedNever().HasMaxLength(150);
            modelBuilder.Entity<Person>().Property(x => x.Address).HasColumnName(@"Address").IsRequired().ValueGeneratedNever().HasMaxLength(250);
            modelBuilder.Entity<Person>().Property<short>(@"Zip").HasColumnName(@"Zip").ValueGeneratedNever();
            modelBuilder.Entity<Person>().HasKey(@"Id");
        }

        partial void CustomizePersonMapping(ModelBuilder modelBuilder);

        #endregion

        #region Number Mapping

        private void NumberMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Number>().ToTable(@"Number");
            modelBuilder.Entity<Number>().Property(x => x.Id).HasColumnName(@"Id").IsRequired().ValueGeneratedOnAdd();
            modelBuilder.Entity<Number>().Property(x => x.NumberString).HasColumnName(@"NumberString").IsRequired().ValueGeneratedNever().HasMaxLength(15);
            modelBuilder.Entity<Number>().HasKey(@"Id");
        }

        partial void CustomizeNumberMapping(ModelBuilder modelBuilder);

        #endregion

        #region City Mapping

        private void CityMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<City>().ToTable(@"City");
            modelBuilder.Entity<City>().Property(x => x.Zip).HasColumnName(@"Zip").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<City>().Property(x => x.Name).HasColumnName(@"Name").IsRequired().ValueGeneratedNever().HasMaxLength(150);
            modelBuilder.Entity<City>().HasKey(@"Zip");
        }

        partial void CustomizeCityMapping(ModelBuilder modelBuilder);

        #endregion

        private void RelationshipsMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Person>().HasMany(x => x.Numbers).WithMany(op => op.People)
                .UsingEntity<Dictionary<string, object>>(
                    @"PersonNumber",
                    x => x.HasOne<Number>().WithMany().HasPrincipalKey(@"Id").HasForeignKey(@"IdN"),
                    x => x.HasOne<Person>().WithMany().HasPrincipalKey(@"Id").HasForeignKey(@"IdP")
                )
                .ToTable(@"PersonNumber");
            modelBuilder.Entity<Person>().HasOne(x => x.City).WithMany(op => op.People).HasForeignKey(@"Zip").IsRequired(true);

            modelBuilder.Entity<City>().HasMany(x => x.People).WithOne(op => op.City).HasForeignKey(@"Zip").IsRequired(true);
        }

        partial void CustomizeMapping(ref ModelBuilder modelBuilder);

        public bool HasChanges()
        {
            return ChangeTracker.Entries().Any(e => e.State == Microsoft.EntityFrameworkCore.EntityState.Added || e.State == Microsoft.EntityFrameworkCore.EntityState.Modified || e.State == Microsoft.EntityFrameworkCore.EntityState.Deleted);
        }

        partial void OnCreated();
    }
}
