//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2021. 04. 01. 16:17:53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace WPF_PhoneBook
{
    public partial class Person {

        public Person()
        {
            this.Numbers = new List<Number>();
            OnCreated();
        }

        public virtual int Id { get; set; }

        public virtual string Name { get; set; }

        public virtual string Address { get; set; }

        public virtual IList<Number> Numbers { get; set; }

        public virtual City City { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
